---
name: bosh

releases:
- name: bosh
  url:
  sha1:
- name: bosh-aws-cpi
  url:
  sha1:

resources_pools:
- name: vms
  network: private
  stemcell:
    url:
    sha1:
  cloud_properties:
    instance_type: t2.medium
    ephemeral_disk: {size: 25_000, type: gp2}
    availability_zone: ap-southeast-1a # <--- Replace with Availability Zone

disk_pools:
- name: disks
  disk_size: 20_000
  cloud_properties: {type: gp2}

networks:
- name: private
  type: manual
  subnets:
  - range: 10.0.0.0/24
    gateway: 10.0.0.1
    dns: [10.0.0.2]
    cloud_properties: {subnet: subnet-b5383dc3} # <--- Replace with Subnet ID
- name: public
  type: vip

jobs:
- name: bosh
  instances: 1

  templates:
  - {name: nats, release: bosh}
  - {name: postgres, release: bosh}
  - {name: blobstore, release: bosh}
  - {name: director, release: bosh}
  - {name: health_monitor, release: bosh}
  - {name: registry, release: bosh}
  - {name: aws_cpi, release: bosh-aws-cpi}

  resource_pools: vms
  persistent_disk_pool: disks

  networks:
  - name: private
    static_ips: [10.0.0.6]
    default: [dns, gateway]
  - name: public
    static_ips: [13.228.122.64] # <--- Replace with Elastic IP
  
  properties:
    nats:
      address: 127.0.0.1
      user: nats
      password: nats-password # <--- Specify your own password
    
    postgres: &db
      listen_address: 127.0.0.1
      host: 127.0.0.1
      user: postgres
      password: postgres-password # <--- Specify your own password
      database: bosh
      adapter: postgres
    
    registry:
      address: 10.0.0.6
      host: 10.0.0.6
      db: *db
      http:
        user: admin
        password: admin # <--- Specify your own password
        port: 25777
    
    blobstore:
      address: 10.0.0.6
      port: 25250
      provider: dav
      director:
        user: director
        password: director-password  # <--- Specify your own password
      agent: 
        user: agent
        password: agent-password # <--- Specify your own password
    
    director:
      address: 127.0.0.1
      name: my-bosh
      db: *db
      cpi_job: aws_cpi
      max_threads: 10
      user_management:
        provider: local
        local:
          users:
          - {name: admin, password: admin} # <--- Specify your own password
          - {name: hm, password: hm-password} # <--- Specify your own password
    
    hm:
      director_account:
        user: hm
        password: hm-password # <--- Specify your own password
      resurrector_enabled: true
    
    aws: &aws
      access_key_id: ACCESS-KEY-ID # <--- Replace with AWS Access Key ID
      secret_access_key: SECRET-ACCESS-KEY # <--- Replace with AWS Secret Key
      default_key_name: my_ec2_instance_key_pair_name
      default_security_groups: [my_security_group_for_bosh]
      region: ap-southeast-1  # <--- Replace with Region
    
    agent: {mbus: "nats://nats:nats-password@10.0.0.6:4222"}

    ntp: &ntp [0.pool.ntp.org, 1.pool.ntp.org] # <--- Replace with your internal NTP servers

cloud_provider:
  template: {name: aws_cpi, release: bosh-aws-cpi}

  ssh_tunnel:
    host: 1.2.3.4 # <--- IP address of BOSH
    port: 22
    user: vcap
    private_key: ./bosh.pem # Path relative to this manifest file

  mbus: "https://mbus:mbus-password@13.228.122.64:6868"
  
  properties:
    aws: *aws
    agent: {mbus: "https://mbus:mbus-password@0.0.0.0:6868"}
    blobstore: {provider: local, path: /var/vcap/micro_bosh/data/cache}
    ntp: *ntp
    env:
      http_proxy: http://my_aws_api_proxy.fqdn:8080
      https_proxy: http://my_aws_api_proxy.fqdn:8080
      no_proxy: 127.0.0.1,my_fqdn,my_ip_address # <--- prefix is not supported